btrfs-progs: dump-tree: fix the chunk type check for system chunks
[BUG]
Commit 408e45feb325 ("btrfs-progs: dump-tree: add extra chunk type
checks") introduced one extra check on when using "btrfs ins dump-tree
-b <bytenr>" option, to prevent end users from passing logical address
belonging to data chunks.

However that check forget that we also have metadata in system chunks,
thus will cause the following false alerts:

 # mkfs.btrfs -f $dev
 # btrfs ins dump-tree -t chunk $dev | grep "owner CHUNK_TREE"
 leaf 22036480 items 4 free space 15781 generation 8 owner CHUNK_TREE
 ^^^ This means we can still print the chunk tree

 # btrfs ins dump-tree -b 22036480 $dev
 btrfs-progs v6.19.1
 ERROR: logical 22036480 is not in a metadata chunk, found chunk 22020096 len 8388608 flags 0x22

[CAUSE]
I'm an idiot and forgot to check system chunks.

[FIX]
Add system chunk type into the check.

Fixes: 408e45feb325 ("btrfs-progs: dump-tree: add extra chunk type checks")
Signed-off-by: Qu Wenruo <wqu@suse.com>