include/kerncompat.h: add fallback for static_assert
The build fails for some uClibc toolchains with:
undefined reference to `static_assert'

This happens because some toolchains do not define the 'static_assert'
macro in <assert.h> even when compiling with -std=gnu11. btrfs-progs
uses static_assert in the container_of macro in include/kerncompat.h.

Fix this by providing a fallback definition using _Static_assert.

Signed-off-by: Shubham Chakraborty <chakrabortyshubham66@gmail.com>