btrfs-progs: fix raid56 reconstruction read
[BUG]
The following script can easily lead to false alerts from
"btrfs check --check-data-csum":

	mkfs.btrfs -f -d raid5 $dev1 $dev2 > /dev/null
	mount $dev1 $mnt
	$fsstress -w -n 64 -d $mnt
	umount $mnt
	btrfs check --check-data-csum $dev1

Which will normally report a lot of csum mismatch on mirror 2:

 Opening filesystem to check...
 Checking filesystem on /dev/test/scratch1
 UUID: e742b7b6-2562-48e5-b411-d50975633045
 [1/8] checking log skipped (none written)
 [2/8] checking root items
 [3/8] checking extents
 [4/8] checking free space tree
 [5/8] checking fs roots
 [6/8] checking csums against data
 mirror 2 bytenr 298909696 csum 0xd800f135 expected csum 0x7f6b1842
 mirror 2 bytenr 298913792 csum 0x1f49b645 expected csum 0x7f6b1842
 ...
 mirror 2 bytenr 1372917760 csum 0x16f78e6b expected csum 0x9462d728
 mirror 2 bytenr 1372921856 csum 0xa972667e expected csum 0x3bea937f
 ERROR: errors found in csum tree
 [7/8] checking root refs
 [8/8] checking quota groups skipped (not enabled on this FS)
 found 2736128 bytes used, error(s) found

And if asan is enabled, it will detect a heap-over-flow:

[6/8] checking csums against data
=================================================================
==6512==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7e982fa2c800 at pc 0x7f883111e4da bp 0x7ffc69e8c9a0 sp 0x7ffc69e8c148
READ of size 65536 at 0x7e982fa2c800 thread T0
    #0 0x7f883111e4d9 in memcpy /usr/src/debug/gcc/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors_memintrinsics.inc:115
    #1 0x560b9f250c4a in read_raid56 kernel-shared/extent_io.c:413
    #2 0x560b9f25100a in read_data_from_disk kernel-shared/extent_io.c:443
    #3 0x560b9f3faa12 in check_extent_csums check/main.c:5964
    #4 0x560b9f3fcaee in check_csum_root check/main.c:6235
    #5 0x560b9f3fcef6 in check_csums check/main.c:6276
    #6 0x560b9f41d168 in cmd_check check/main.c:11082
    #7 0x560b9f1f04fb in cmd_execute cmds/commands.h:126
    #8 0x560b9f1f1cc8 in main /home/adam/btrfs-progs/btrfs.c:474
    #9 0x7f8830c27634  (/usr/lib/libc.so.6+0x27634) (BuildId: 2f722da304c0a508c891285e6840199c35019c8d)
    #10 0x7f8830c276e8 in __libc_start_main (/usr/lib/libc.so.6+0x276e8) (BuildId: 2f722da304c0a508c891285e6840199c35019c8d)
    #11 0x560b9f1f03d4 in _start (/home/adam/btrfs-progs/btrfs+0x883d4) (BuildId: 2fde8cac91b9fec1b45e1b5145ee594466b76396)

0x7e982fa2c800 is located 0 bytes after 65536-byte region [0x7e982fa1c800,0x7e982fa2c800)
allocated by thread T0 here:
    #0 0x7f8831120cb5 in malloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:67
    #1 0x560b9f250874 in read_raid56 kernel-shared/extent_io.c:348
    #2 0x560b9f25100a in read_data_from_disk kernel-shared/extent_io.c:443
    #3 0x560b9f3faa12 in check_extent_csums check/main.c:5964
    #4 0x560b9f3fcaee in check_csum_root check/main.c:6235
    #5 0x560b9f3fcef6 in check_csums check/main.c:6276
    #6 0x560b9f41d168 in cmd_check check/main.c:11082
    #7 0x560b9f1f04fb in cmd_execute cmds/commands.h:126
    #8 0x560b9f1f1cc8 in main /home/adam/btrfs-progs/btrfs.c:474
    #9 0x7f8830c27634  (/usr/lib/libc.so.6+0x27634) (BuildId: 2f722da304c0a508c891285e6840199c35019c8d)
    #10 0x7f8830c276e8 in __libc_start_main (/usr/lib/libc.so.6+0x276e8) (BuildId: 2f722da304c0a508c891285e6840199c35019c8d)
    #11 0x560b9f1f03d4 in _start (/home/adam/btrfs-progs/btrfs+0x883d4) (BuildId: 2fde8cac91b9fec1b45e1b5145ee594466b76396)

SUMMARY: AddressSanitizer: heap-buffer-overflow kernel-shared/extent_io.c:413 in read_raid56
Shadow bytes around the buggy address:
  0x7e982fa2c580: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7e982fa2c600: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7e982fa2c680: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7e982fa2c700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7e982fa2c780: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x7e982fa2c800:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7e982fa2c880: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7e982fa2c900: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7e982fa2c980: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7e982fa2ca00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7e982fa2ca80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):

[CAUSE]
During read of mirrors other than mirror 0/1 from RAID56 profiles,
btrfs-progs go through the following call chain:

 read_data_from_disk()
 |- btrfs_map_block()
 |  Note that @read_len returned by btrfs_map_block() is always
 |  BTRFS_STRIPE_LEN.
 |
 \- read_raid56()
    | Which does read out all stripes, but there is no extra checks
    | against if the logical range crosses stripe boundaries.
    |
    |- raid56_recov()
    |  Which rebuilds the target stripe.
    |
    |- memcpy(buf, pointers[failed_a] + (logical - full_stripe_start) %
              BTRFS_STRIPE_LEN, len);

If @logical is not at the begining of a stripe, then @logical + @len
will go beyond the stripe buffer size, causing gargage into the target
buffer.

[FIX]
Calculate the correct read length inside the data stripe for RAID56
inside read_data_from_disk().

And add extra ASSERT()s inside read_raid56().

Signed-off-by: Qu Wenruo <wqu@suse.com>