btrfs: automatically cleanup aborted transaction on fs close
[BUG]
Inspired by a recent bug report that due to an incorrect use case
(using mkfs.btrfs --reflink option with NODATACOW files), that a failed
mkfs.btrfs will lead to the following leaked extent buffer:

  btrfs-progs v6.17.1
  See https://btrfs.readthedocs.io for more information.

  Rootdir from:       /var/tmp/.#repartc2f366b20457a16d
    Compress:         no
  ERROR: cannot clone range: Invalid argument
  ERROR: failed to write /var/tmp/.#repartc2f366b20457a16d/var/lib/systemd/catalog/database
  ERROR: failed to add file extents for inode 265 ('/var/tmp/.#repartc2f366b20457a16d/var/lib/systemd/catalog/database'): Invalid argument
  ERROR: unable to traverse directory /var/tmp/.#repartc2f366b20457a16d: -22
  ERROR: error while filling filesystem: Invalid argument
  WARNING: reserved space leaked, flag=0x4 bytes_reserved=16384
  extent buffer leak: start 30408704 len 16384
  WARNING: dirty eb leak (aborted trans): start 30408704 len 16384

[CAUSE]
The error path of btrfs_mkfs_fill_dir() has properly called
btrfs_abort_transaction().

But btrfs_abort_transaction() itself only marks the fs error but do
nothing to cleanup any dirtied extent buffer or whatever.

The reason is we can not easily do the full transaction abort cleanup
including freeing the trans handle pointer, thus we need to call
btrfs_commit_transaction() to do the proper cleanup.

[FIX]
I considered calling btrfs_commit_transaction() for every
btrfs_abort_transaction() call, but it is a lot of work and never looks
good to me.

So instead I add the proper cleanup into close_ctree_fs_info(), that if
we detected an aborted transaction that is not yet commited, do the
proper cleanup so we won't have leaked dirty extent buffers:

Issue: #1073
Signed-off-by: Qu Wenruo <wqu@suse.com>