btrfs-progs: disable block-group-tree feature if dependency is missing
Currently mkfs.btrfs will fail with the following features:

  # mkfs.btrfs -O block-group-tree,^no-holes $dev
  btrfs-progs v6.17.1
  See https://btrfs.readthedocs.io for more information.

  ERROR: block group tree requires no-holes and free-space-tree features

That's due to the artificial feature requirements from block-group-tree,
which requires no-holes and free-space-tree.

But such mandatory rejection will block our migration to the new default
block-group-tree tree features as a lot of no-holes test cases will cause
false alerts (and we do not have plan to deprecate explicit holes yet,
or do we?).

So to avoid the new default block-group-tree feature from causing tons of
false alerts, automatically disable block-group-tree feature if the end user
disables no-holes or free-space-tree features.

Now the above command will success, but with extra warnings and
block-group-tree disabled.

  # mkfs.btrfs -O block-group-tree,^no-holes $dev
  btrfs-progs v6.17.1
  See https://btrfs.readthedocs.io for more information.

  WARNING: disabling block-group-tree feature due to missing no-holes and free-space-tree features
  Label:              (null)
  UUID:               3c7adb81-c0c3-4980-8ef3-485019e5d8c4
  Node size:          16384
  Sector size:        4096	(CPU page size: 4096)
  Filesystem size:    1.00GiB
  Block group profiles:
    Data:             single            8.00MiB
    Metadata:         DUP              51.19MiB
    System:           DUP               8.00MiB
  SSD detected:       no
  Zoned device:       no
  Features:           extref, skinny-metadata, free-space-tree
  Checksum:           crc32c
  ...

Signed-off-by: Qu Wenruo <wqu@suse.com>
Signed-off-by: David Sterba <dsterba@suse.com>