mkfs/main.c: fix build without zoned
Fix the following build failure raised when zoned is disabled since
version 5.16.1 and
https://github.com/kdave/btrfs-progs/commit/88895a920ff5b0969ec22fdc9f4511b17dd14806:

mkfs/main.o: In function `main':
main.c:(.text.startup+0xc90): undefined reference to `zoned_profile_supported'

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>