btrfs-progs: check: auto-detect chunk level when --chunk-root is specified
[BUG]
There is a bug report that, when using --chunk-root option, if the
specified chunk root tree block has a different level than the one in
the super block, btrfs check will reject the run:

  ERROR: root [3 0] level 0 does not match 1
  ERROR: cannot read chunk root
  ERROR: cannot open file system
  Opening filesystem to check...

[CAUSE]
During btrfs_setup_chunk_tree_and_device_map(), although it accepts a
@chunk_root_bytenr parameter, it still uses the chunk root level from
the super block.

Thus if the provided chunk root is at a different level, it will still
be rejected.

[FIX]
Read out the tree block at @chunk_root_bytenr, and use the level from
the tree block instead.

Pull-request: #1037
Link: https://lore.kernel.org/linux-btrfs/CAKZK7uxiRmDxk-1goC4yj7QZPSmL-=GAoAuF=OdekbSNVrG8fg@mail.gmail.com/
Signed-off-by: Qu Wenruo <wqu@suse.com>