btrfs-progs: device usage: fix error reporting number of devices 0 != 1
Due to refactoring in 88c25674c7c0d0 ("btrfs-progs: convert device info
to struct array") the variable tracking number of devices was not
updated and led to an error.

  $ btrfs device usage /path
  ERROR: unexpected number of devices: 0 != 1
  ...

Issue: #697
Signed-off-by: David Sterba <dsterba@suse.com>